# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Petrolography' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Petrolography
    pod 'Firebase/Core'

  target 'PetrolographyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetrolographyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
